name: Deploy Render

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar Render
        run: curl -X GET "https://api.render.com/deploy/srv-d9db00gk1i2s73ekhrng?key=8qMFfH5Fm1g"
